version: "3.8"

services:
  db:
    image: postgres:13
    env_file: .env
    container_name: db
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webserver-minesweeper

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./keys:/etc/nginx/keys/
    networks:
      - webserver-minesweeper

  web:
    build: .
    container_name: web
    command: gunicorn --certfile=keys/cert.pem --keyfile=keys/key_no_pass.pem --bind 0.0.0.0:5000 manage:app
    volumes:
      - .:/usr/src/app/
    env_file: .env
    ports:
      - ${PORT}:5000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=${DATABASE_URI}

networks:
  webserver-minesweeper:
    driver: bridge
volumes:
  pgdata:
